<a href="https://colab.research.google.com/github/vasist05/eda-colab-lab/blob/main/numpy_lab_011.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Fundamentals-week1

THIS IS MY FIRST NUMPY lab PROGRAMS

In [ ]:
#a. Create a 1D array with numbers from 10 to 20.
import numpy as np #aliacing
a=np.arange(10,21)
print(a)


[10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#b. Create a 3 × 4 array filled with 0s using nested lists.
import numpy as np
b=np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print(b)



[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
#c. Create a 2 × 3 × 2 array using nested lists
c=np.array([[[1,2],[1,2],[1,2]],[[1,2],[1,2],[1,2]]])
print(c)

[[[1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]]]


In [ ]:
#d. Print all the arrays. Also print their shape and number of dimensions (ndim).
print(a)

print(b)

print(c)
print("shape of array a is :" ,a.shape)
print("shape of array b is :",b.shape)
print("shape of array c is :",c.shape)
print("dimension of array a is :" ,a.ndim)
print("dimension of array b is :",b.ndim)
print("dimension of array c is :",c.ndim)


[10 11 12 13 14 15 16 17 18 19 20]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]]]
shape of array a is : (11,)
shape of array b is : (3, 4)
shape of array c is : (2, 3, 2)
dimension of array a is : 1
dimension of array b is : 2
dimension of array c is : 3


2.  Create Arrays Using NumPy Functions

In [ ]:
#a. Create a 1D array of 6 elements, all filled with 7.
d=np.full(6,7)
print(d)


[7 7 7 7 7 7]


In [ ]:
#b. Print the array along with its shape and data type.
print("shape and data type of array d is",d.shape, "and",d.dtype)

shape and data type of array d is (6,) and int64


In [ ]:
#c. Create an array from 0 to 30 (excluding 30) with a step of 3 using arange().
e=np.arange(0,30,3)
print(e)

[ 0  3  6  9 12 15 18 21 24 27]


# **NumPy Fundamentals-week 2**
Write Python programs using NumPy to perform indexing, slicing and arithmetic operations.



 **Exercise 1: Basic Indexing**
Create a 1D NumPy array containing the elements [12, 25, 38, 47, 59, 61] and a 3 × 3 NumPy array containing the values from 10 to 90. Perform the following operations:
<hr>
1)Display the first and last elements of the 1D array.
<br>
2)Access the fourth element of the 1D array.
<br>
3)Retrieve the element at the first row and third column of the 2D array.<br>
4)Retrieve the element at the third row and second column.<br>
5)Display the last element of the 2D array using negative indexing.


1)Display the first and last elements of the 1D array.

In [ ]:
import numpy as np
arr=np.array([12, 25, 38, 47, 59, 61] )
arr
f=arr[0]
l=arr[-1]
print("the first and last element are:",f," ",l)

the first and last element are: 12   61


2)Access the fourth element of the 1D array

In [ ]:
print("the fourth element of the 1d array is :",arr[3])

the fourth element of the 1d array is : 47


In [ ]:
arr2d=np.array([11,21,84,56,32,74,14,55,63]).reshape(3,3)
print(arr2d)
print()
#3)Retrieve the element at the first row and third column of the 2D array.
print("the element at the first row and third column of the 2D array is :",arr2d[0,2])


[[11 21 84]
 [56 32 74]
 [14 55 63]]

the element at the first row and third column of the 2D array is : 84


In [ ]:
#4)Retrieve the element at the third row and second column.
print(" the element at the third row and second column:",arr2d[2,1])

 the element at the third row and second column: 55


In [ ]:
#5)Display the last element of the 2D array using negative indexing
print(" the last element of the 2D array using negative indexing is :",arr2d[-1,-1])

 the last element of the 2D array using negative indexing is : 63


##Exercise 2: Array Slicing
#### Create a 5 × 5 NumPy array containing integers from 1 to 25. <br>
Using slicing operations:


In [ ]:
#Extract the first row.
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print(arr,"\n")
print(" the first row is:",arr[0])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

 the first row is: [1 2 3 4 5]


In [ ]:
#Extract the last column.
print("the last column is:",arr[:,4])
print("the last column is:",arr[:,-1])

the last column is: [ 5 10 15 20 25]
the last column is: [ 5 10 15 20 25]


In [ ]:
#Display rows 2 to 4.
print("the elements in rows 2 to 4 are:\n",arr[2:5])

the elements in rows 2 to 4 are:
 [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#Extract the middle 3 × 3 subarray
print(arr[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
#Display alternate rows.
print(arr[::2])#odd alternating rows
print()
print(arr[1::2])#even alternating rows

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [ ]:
#Extract the first three columns.
print(arr[:,0:3])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]]


##Exercise 3: Boolean Indexing
<hr>
Create a NumPy array representing students' marks: [45, 68, 91, 34, 82, 76, 59,99, 41].
<hr>
 Using boolean indexing:
Display marks greater than 75.<br>
Display marks less than 40.<br>
Display all even marks.<br>
Display marks between 50 and 80 (inclusive).<br>
Count the number of students scoring above 60.


In [ ]:
import numpy as np
arr=np.array( [45, 68, 91, 34, 82, 76, 59, 99, 41])
m1=arr>75
print(m1,"\n")
#Using boolean indexing: Display marks greater than 75.
print(arr[m1])

[False False  True False  True  True False  True False] 

[91 82 76 99]


In [ ]:
#Display marks less than 40.
m2=arr<40
print(m2,"\n")
print(arr[m2])

[False False False  True False False False False False] 

[34]


In [ ]:
#Display all even marks
print(arr[arr%2==0])

[68 34 82 76]


In [ ]:
#Display marks between 50 and 80 (inclusive).
m3=(arr>=50) & (arr<=80)
print(m3,"\n")
print(arr[m3])


[False  True False False False  True  True False False] 

[68 76 59]


In [ ]:
#Count the number of students scoring above 60.
m4=arr>60
a=arr[m4]
print(len(a))
a

5


array([68, 91, 82, 76, 99])

## Exercise 4: Fancy Indexing


---

Create a 1D NumPy array containing the elements:
 [11, 22, 33, 44, 55, 66, 77, 88, 99] and a 3 × 3 matrix.
<hr>




In [ ]:
import numpy as np
arr=np.array([11, 22, 33, 44, 55, 66, 77, 88, 99] )
arr

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [ ]:
#Perform the following using fancy indexing:
#Retrieve the elements at indices 0, 2, 4, 6, and 8.
l=[0,2,4,6,8]
print(arr[l])


[11 33 55 77 99]


In [ ]:
#Select the first and third rows of the matrix.
arr=arr.reshape(3,3)
print(arr,"\n")
l=[0,2]
print("the 1 st and 3rd rows are:\n",arr[l])

[[11 22 33]
 [44 55 66]
 [77 88 99]] 

the 1 st and 3rd rows are:
 [[11 22 33]
 [77 88 99]]


In [ ]:
#Retrieve the diagonal elements using index arrays.
rows=[0,1,2]
col=[0,1,2]
print("the diagonal elements are:\n")
print(arr[rows,col])

the diagonal elements are:

[11 55 99]


In [ ]:
#Extract the corner elements of the matrix.
row=[0,0,2,2]
col=[0,2,0,2]
print(arr[row,col])

[11 33 77 99]


In [ ]:
#Rearrange the rows of the matrix in the order 3, 1, 2.
r3=arr[2]
r1=arr[0]
r2=arr[1]
narr=np.array([r3,r1,r2])
print(narr)

[[77 88 99]
 [11 22 33]
 [44 55 66]]


##Exercise 5: Combined Indexing Techniques<hr>
A company's quarterly sales data for four branches is stored in a 4 × 4 NumPy array.
 Perform the following operations:



In [ ]:
arr=np.arange(100,116).reshape(4,4)
arr

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115]])

In [ ]:
#Retrieve the sales value of the second branch during the third quarter
print(arr[1,2])


106


In [ ]:
#Display the sales data of the first two branches
print(arr[:2])

[[100 101 102 103]
 [104 105 106 107]]


In [ ]:
#Extract the sales values greater than 200 using boolean indexing
b1=arr>200
b1
print(arr[b1])

[]


In [ ]:
#Retrieve the sales values corresponding to the following positions using fancy indexing:
#(1st row, 2nd column)
#(3rd row, 4th column)
#(4th row, 1st column)

rows = [0, 2, 3]
cols = [1, 3, 0]
print(arr[rows, cols])

[101 111 112]


In [ ]:
#Display the last two quarters' sales for all branches using slicing.
print(arr[:,2:])

[[102 103]
 [106 107]
 [110 111]
 [114 115]]


#Week-3: (28/7/2026, Tue) : Advanced NumPy Operations

##Write Python programs using Transposition and reshaping arrays, Random number generation, Aggregate functions and axis operations


##Exercise 1: Transposition & Reshaping arrays


In [ ]:
#1.     Create a 3×4 NumPy array with integers from 0 to 11. Transpose the array using .T and verify the shape becomes 4×3. Print both arrays and observe the structural changes. (Transposing 2D Matrix)
import numpy as np
arr=np.arange(0,12).reshape(3,4)
transarr=arr.T
print(transarr)
print()
print(arr)
print("shape of arr is:",arr.shape)
print()
print("shape of arr is:",transarr.shape)


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape of arr is: (3, 4)

shape of arr is: (4, 3)


In [ ]:
#2. Create a 3D array of shape (2, 3, 4) with sequential numbers using np.arange() and reshape. Transpose it using .transpose(1, 0, 2) to reorder the shape as (3, 2, 4). (Transpose a 3-D Array)
# Print the new shape and verify that data was rearranged accordingly.
arr=np.arange(0,24).reshape(2,3,4)
print(arr)
print()
transarr=arr.transpose(1,0,2)
print(transarr)
print()
print("shape of transarr is:",transarr.shape)
print()



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

shape of transarr is: (3, 2, 4)



In [ ]:
#4. 	Generate a 6×2 array. Transpose it using .T, and then apply np.swapaxes(array, 0, 1) on the original array.
#Show that both results are the same and explain why. (Compare Transpose and Swapaxes)
arr=np.arange(0,12).reshape(6,2)
arr1=arr.T
arr2=np.swapaxes(arr,0,1)
print(arr1)
print()
print(arr2)
print(arr1==arr2)


[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [ ]:
#5. 	Create a 3D array with shape (2, 4, 3). Use np.swapaxes to swap axes 0 and 2, and print the new shape.
# Check how the data has been reorganized by printing slices from both arrays. (Swapaxes on a 3D Array)
arr=np.arange(1,25).reshape(2,4,3)
print(arr)
arr2=np.swapaxes(arr,2,0)
print(arr2)
print("shape of arr2 is:",arr2.shape)
print()
print(arr[1,1])
print(arr2[1,1])


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
[[[ 1 13]
  [ 4 16]
  [ 7 19]
  [10 22]]

 [[ 2 14]
  [ 5 17]
  [ 8 20]
  [11 23]]

 [[ 3 15]
  [ 6 18]
  [ 9 21]
  [12 24]]]
shape of arr2 is: (3, 4, 2)

[16 17 18]
[ 5 17]


##Exercise 2: Random Number Generation

In [ ]:
#Use np.random.permutation to generate multiple random permutations of an array containing integers from 1 to 20.
#Ensure the original array remains unchanged after each permutation.
arr=np.arange(1,21)
rng=np.random.default_rng()
arr2=rng.permutation(arr)
arr2
print(arr)
print()
print(arr2)
print()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[ 7 16 10  1  8  3 18  4  9  2 17 12 20 19  5  6 14 13 15 11]



In [ ]:
# Using np.random.shuffle, create an array of characters ['A', 'B', 'C', 'D', 'E'] and shuffle its elements in-place.
#Print the array before and after shuffling to confirm it was modified.
arr=np.array(['A', 'B', 'C', 'D', 'E'])
arr2=rng.shuffle(arr)
print(arr2)
print(arr)



None
['A' 'B' 'E' 'C' 'D']


In [ ]:
 #Create a 5×4 matrix of random integers between 10 and 99 using np.random.randint.
 #Find the maximum value in each row and count how many values in the matrix are greater than 50.
 arr=np.random.randint(10,99,20).reshape(5,4)
 print(arr)
 maxi=arr.max(axis=1)
 maxi
 x=np.sum(arr>50)
 x


[[95 87 72 69]
 [38 58 78 12]
 [12 50 60 84]
 [76 25 16 46]
 [94 47 15 27]]


np.int64(10)

In [ ]:
 #Use np.random.standard_normal to generate a 6×6 matrix of normally distributed random numbers with mean 0 and standard deviation 1.
 # Compute and display the sample mean and standard deviation.
 arr=np.random.standard_normal(36)
 mean=arr.mean(axis=0)
 mean


np.float64(-0.22671764705515957)

In [ ]:
# Use np.random.normal to generate 1000 random values from a normal distribution with a mean of 100 and standard deviation of 15.
arr=np.random.normal(100,15,1000)
arr

array([ 98.12701742,  81.47715988,  91.57758465,  88.12136021,
       106.86229148,  91.827312  , 121.99407902,  98.56990508,
        99.31546351, 112.60490068,  92.47772615, 127.18281971,
       105.5593376 ,  84.5750509 ,  79.61873417,  85.36102775,
        99.27760254, 106.84027982, 110.65316211,  94.69096024,
        88.27636485, 103.47293893,  95.25286447,  85.17522627,
       110.07668383, 112.48329901,  99.00230914, 107.889807  ,
       100.50820954, 108.40493528, 108.29905921, 106.28577413,
        88.95118389,  92.21763541, 103.99103858, 107.18877918,
        91.10173701, 123.45896697, 105.65625094,  80.34249365,
        92.10656863, 125.34163595,  98.27011885,  95.0081868 ,
        99.58771835, 121.99683943,  82.09083733, 102.2495675 ,
        91.41065766,  80.76677456,  93.68040687, 117.68228836,
        98.77631723,  73.16751659,  85.09922724,  93.91658596,
        84.19890129,  90.00134791, 126.52779469,  91.74232106,
       103.83232404,  80.40925258, 108.53374691, 122.47

## Exercise 3: Aggregate functions and Axis Operations


In [ ]:
#Create a 5×4 NumPy array of random integers between 10 and 50, then
# compute row-wise sums, column-wise sums, and identify the row with the highest sum.
import numpy as np
rng=np.random.default_rng()
arr=random.randint(low=10,high=51,size=(5,4))
print(arr)
print("rsum is :",arr.sum(axis=1))
print("csum is:",arr.sum(axis=0))
rarr=arr.sum(axis=1)
print("row with highest sum is:",rarr.argmax())



[[40 37 15 31]
 [30 42 49 31]
 [23 35 10 26]
 [41 22 48 30]
 [46 26 32 13]]
rsum is : [123 152  94 141 117]
csum is: [180 162 154 131]
row with highest sum is: 1


In [ ]:
#Generate a 6×4 NumPy array of random integers between 50 and 100, then find row-wise means, column-wise means, column-wise standard deviations,
# and determine the column with the highest standard deviation.
arr=random.randint(low=50,high=101,size=(6,4))
print(arr)
rmean=arr.mean(axis=1)
print(rmean)
cmean=arr.mean(axis=0)
print(cmean)
rstd_dev=arr.std(axis=1)
print(rstd_dev)
cstd_dev=arr.std(axis=0)
print(cstd_dev)
print("the column with higest std deviation is:",cstd_dev.argmax())
#argmax() gives us index with max element


[[73 77 67 88]
 [65 69 90 73]
 [71 70 66 59]
 [81 61 92 76]
 [83 97 68 56]
 [89 68 84 77]]
[76.25 74.25 66.5  77.5  76.   79.5 ]
[77.         73.66666667 77.83333333 71.5       ]
[ 7.66077672  9.52299848  4.71699057 11.1467484  15.44344521  7.88986692]
[ 8.08290377 11.426091   11.11180553 10.9658561 ]
the column with higest std deviation is: 1


In [ ]:
#Create a 6×6 NumPy array of random floats from a normal distribution (mean 0, standard deviation 1),
# then for each column calculate (max - min) and identify the column with the largest range.
import numpy as np
rng=np.random.default_rng()
arr=rng.standard_normal(size=(6,6))
cmax=arr.max(axis=0)
cmin=arr.min(axis=1)
#print("max value in each col is:",cmax)
#print("min value in each col is:",cmin)
range=cmax-cmin
print("the range of cols is :",range)
print("the column with largest range is:",range.argmax())

the range of cols is : [1.49319472 1.97690653 2.37733771 0.47975411 2.95685362 2.2899882 ]
the column with largest range is: 4


In [ ]:
#Create a 1D NumPy array of 12 random integers between 100 and 500,
#then compute the cumulative sum, cumulative product, and cumulative maximum of its elements.
arr=random.randint(low=100,high=500,size=12)
print("the orginal array:",arr)
cumsum=arr.cumsum()
print("the cumulative sum of array is:",arr.cumsum())
print("the cumulative product of array is:",arr.cumprod())
print("the cumulative maximum of its elements is :",cumsum.argmax())





the orginal array: [138 282 157 336 196 126 329 244 124 438 173 194]
the cumulative sum of array is: [ 138  420  577  913 1109 1235 1564 1808 1932 2370 2543 2737]
the cumulative product of array is: [                 138                38916              6109812
           2052896832         402367779072       50698340163072
    16679753913650688  4069859954930767872  6600544421257322496
 -5100363061692350464  3080905865281847296  7399927505972723712]
the cumulative maximum of its elements is : 11


# Week-4: (4/8/2026, Tue) : Series and Data Frame creation


In [ ]:
#Create a pandas Series object of 10 random integers and display its attributes (index, values, dtype, size, shape).
import pandas as pd
import numpy as np
s=pd.Series(np.random.randint(1,100,size=10))
print(s)

print("the index values are:",s.index)
print("the values in series obj are:",s.values)
print("dtype:",s.dtype)
print("size:",s.size)
print("shape:",s.shape)


0    15
1    17
2    57
3    37
4    99
5    25
6    66
7    49
8    34
9    42
dtype: int64
the index values are: RangeIndex(start=0, stop=10, step=1)
the values in series obj are: [15 17 57 37 99 25 66 49 34 42]
dtype: int64
size: 10
shape: (10,)


In [ ]:
#Create a students DataFrame with columns Name, RollNo, Marks1, Marks2, Marks3 from lists/arrays/Dictionary and display the first 5 rows.
import pandas as pd
data = {
    "Name": ["vaist", "geeetha", "sohan", "gopika", "vaibhav", "maanvitha","ujjwal"],
    "Rollno": [11,12,13,18,16,52,61],
    "Marks1": [85, 90, 78, 88, 92, 80,96],
    "Marks2": [82, 95, 75, 91, 89, 84,45],
    "Marks3": [88, 93, 80, 90, 94, 86,91]
}
students = pd.DataFrame(data)
#print(students)
print(students.head(5))

      Name  Rollno  Marks1  Marks2  Marks3
0    vaist      11      85      82      88
1  geeetha      12      90      95      93
2    sohan      13      78      75      80
3   gopika      18      88      91      90
4  vaibhav      16      92      89      94


In [ ]:
#Create a DataFrame by loading any relevant dataset from Kaggle in .CSV format and display the first 3 rows of the DataFrame,
# display its index, shape, dimension and the number of columns. (Hint: df.head(10))
#from google.colab import files
#uploaded = files.upload()
df=pd.read_csv('/content/sample(011).csv.csv')
print(df.head(3))
print("Index:", df.index)
print("Shape:", df.shape)
print("Dimension:", df.ndim)
print("Number of Columns:", len(df.columns))






    result  table                  timestamp                        member  \
0  _result      0  2026-07-03 08:09:43+00:00  4Y4tgCUKVoTbvnVrrN8AETclnTG2   
1  _result      0  2026-07-03 08:10:44+00:00  4Y4tgCUKVoTbvnVrrN8AETclnTG2   
2  _result      0  2026-07-03 08:11:46+00:00  4Y4tgCUKVoTbvnVrrN8AETclnTG2   

    humidity  temperature  
0  42.900002    26.299999  
1  42.799999    26.299999  
2  42.799999    26.299999  
Index: RangeIndex(start=0, stop=260788, step=1)
Shape: (260788, 6)
Dimension: 2
Number of Columns: 6


#week 5-Series and Data Frame creation-11/08/26


###creating dataframe

In [39]:
import pandas as pd
df=pd.read_csv('/content/sleep_doomscrolling_habits.csv')

df

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,occupation_status,country_region,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category
0,D30000,22,13.0,1.85,2,5.4,8.1,19.0,2,155.0,...,Unemployed,Germany,Tablet,Meditation/Journaling,Yes,Yes,Yes,No,Yes,Good
1,D30001,18,90.0,3.61,3,29.6,7.0,31.0,3,82.0,...,Student,India,Smartphone,Meditation/Journaling,No,Yes,Yes,No,Yes,Poor
2,D30002,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,...,Student,India,Laptop,Reading,No,Yes,No,Yes,Yes,Fair
3,D30003,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,...,NaN,United States,Smartphone,No Fixed Routine,No,Yes,Yes,No,No,Fair
4,D30004,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,...,Employed Part-time,United States,Smartphone,Watching Videos,No,No,No,No,No,Fair
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,D30995,26,85.0,3.56,4,25.4,7.6,34.0,1,169.0,...,Student,India,Tablet,Meditation/Journaling,No,Yes,Yes,Yes,Yes,Poor
996,D30996,23,3.0,1.10,1,10.7,7.5,31.0,1,34.0,...,Student,United States,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Fair
997,D30997,15,28.0,4.38,1,30.6,9.2,20.0,0,100.0,...,Employed Full-time,United States,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Good
998,D30998,22,23.0,1.84,0,27.9,6.9,41.0,2,45.0,...,Student,India,Tablet,Watching Videos,No,Yes,Yes,Yes,No,Fair


###problems

In [40]:
#1)Perform label-based (.loc) to select specific students’ details and marks and positional
 #(.iloc) indexing to slice rows 2–5 with selected columns.

print(df.loc[[2,3,5,433],["age","total_daily_screen_time_hours"]])#selecting specific students
df.iloc[1:5,[5,10,14,21,29]]

     age  total_daily_screen_time_hours
2     37                           5.15
3     27                           3.74
5     21                           5.20
433   25                           3.20


,avg_doomscroll_session_minutes,anxiety_score,number_of_news_apps_used,country_region,sleep_quality_category
1,29.6,5,2,India,Poor
2,15.5,2,0,India,Fair
3,51.4,6,1,United States,Fair
4,32.2,5,3,United States,Fair


In [41]:
#Use Boolean indexing to filter students with Marks1 > 70, calculate a Total column,
# and add a Result column with Pass/Fail status.
##"similar program"
d1=df[df['bedtime_screen_time_minutes']>150]#students whose bedtime screen time is more than 150 mins.
df["total"]=df["doomscroll_sessions_per_night"]+df['sleep_latency_minutes']+df['anxiety_score']
df
df["g/b"]=df["total"].apply(lambda x:"good" if x<=30 else "bad")##first we filtered in total col by using lambda function and.apply() and
                                                                #adding a new col using df["g/b"]=
df



,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category,total,g/b
0,D30000,22,13.0,1.85,2,5.4,8.1,19.0,2,155.0,...,Tablet,Meditation/Journaling,Yes,Yes,Yes,No,Yes,Good,26.0,good
1,D30001,18,90.0,3.61,3,29.6,7.0,31.0,3,82.0,...,Smartphone,Meditation/Journaling,No,Yes,Yes,No,Yes,Poor,39.0,bad
2,D30002,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,...,Laptop,Reading,No,Yes,No,Yes,Yes,Fair,29.0,good
3,D30003,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,...,Smartphone,No Fixed Routine,No,Yes,Yes,No,No,Fair,41.0,bad
4,D30004,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,...,Smartphone,Watching Videos,No,No,No,No,No,Fair,26.0,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,D30995,26,85.0,3.56,4,25.4,7.6,34.0,1,169.0,...,Tablet,Meditation/Journaling,No,Yes,Yes,Yes,Yes,Poor,48.0,bad
996,D30996,23,3.0,1.10,1,10.7,7.5,31.0,1,34.0,...,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Fair,37.0,bad
997,D30997,15,28.0,4.38,1,30.6,9.2,20.0,0,100.0,...,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Good,24.0,good
998,D30998,22,23.0,1.84,0,27.9,6.9,41.0,2,45.0,...,Tablet,Watching Videos,No,Yes,Yes,Yes,No,Fair,44.0,bad


In [ ]:
#Display the DataFrame attributes shape, columns, index, ndim, and size.
print("shape:",df.shape)
print("size:",df.size)
print("index:",df.index)
print("ndim:",df.ndim)
print("columns:",df.columns)
df[2:10]


shape: (1000, 33)
size: 33000
index: RangeIndex(start=0, stop=1000, step=1)
ndim: 2
columns: Index(['respondent_id', 'age', 'bedtime_screen_time_minutes',
       'total_daily_screen_time_hours', 'doomscroll_sessions_per_night',
       'avg_doomscroll_session_minutes', 'sleep_hours_per_night',
       'sleep_latency_minutes', 'number_of_night_wakeups',
       'caffeine_intake_mg_per_day', 'anxiety_score', 'stress_score',
       'sleep_quality_score', 'daytime_fatigue_score',
       'number_of_news_apps_used', 'phone_checks_per_night',
       'exercise_minutes_per_day', 'days_since_last_digital_detox',
       'weekly_sleep_debt_hours', 'gender', 'occupation_status',
       'country_region', 'primary_device_used_at_night',
       'bedtime_routine_type', 'uses_night_mode', 'keeps_phone_in_bedroom',
       'consumes_negative_news_content', 'uses_sleep_tracking_app',
       'doomscroller', 'sleep_quality_category', 'total', 'g', 'g/b'],
      dtype='object')


,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category,total,g,g/b
2,D30002,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,...,Reading,No,Yes,No,Yes,Yes,Fair,29.0,good,good
3,D30003,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,...,No Fixed Routine,No,Yes,Yes,No,No,Fair,41.0,bad,bad
4,D30004,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,...,Watching Videos,No,No,No,No,No,Fair,26.0,good,good
5,D30005,21,81.0,5.20,4,19.5,7.9,39.0,2,61.0,...,Watching Videos,No,Yes,No,No,Yes,Fair,48.0,bad,bad
6,D30006,34,56.0,3.75,3,18.7,8.8,45.0,1,166.0,...,Scrolling Social Media,No,Yes,No,No,Yes,Good,51.0,bad,bad
7,D30007,26,40.0,2.41,3,13.7,7.7,36.0,2,54.0,...,Scrolling Social Media,Yes,Yes,Yes,Yes,Yes,Poor,43.0,bad,bad
8,D30008,32,77.0,3.38,4,19.2,7.8,29.0,1,127.0,...,Reading,Yes,Yes,No,No,Yes,Fair,37.0,bad,bad
9,D30009,34,23.0,2.46,2,7.8,6.4,18.0,3,97.0,...,Reading,No,No,No,No,No,Poor,24.0,good,good


In [ ]:
#Use .loc and Boolean indexing to select students from the AI & DS department who have an average mark above 70.
#instead of ai&ds i will take india country region and total >15
f=df.loc[:,"country_region"]
a=df[df.loc[:,"country_region"]=="India"]
b=df.loc[df["country_region"]=="India"]


,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category,total,g,g/b
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
992,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
995,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
998,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True


In [ ]:
df.iloc[[-1,-2,-3]]

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category,total,g,g/b
999,D30999,23,35.0,1.66,2,16.2,7.5,27.0,2,63.0,...,Scrolling Social Media,No,Yes,Yes,No,Yes,Fair,37.0,bad,bad
998,D30998,22,23.0,1.84,0,27.9,6.9,41.0,2,45.0,...,Watching Videos,No,Yes,Yes,Yes,No,Fair,44.0,bad,bad
997,D30997,15,28.0,4.38,1,30.6,9.2,20.0,0,100.0,...,Scrolling Social Media,No,Yes,No,No,No,Good,24.0,good,good


In [ ]:

df.head(5)
df.tail(5)



,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,occupation_status,country_region,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category
995,D30995,26,85.0,3.56,4,25.4,7.6,34.0,1,169.0,...,Student,India,Tablet,Meditation/Journaling,No,Yes,Yes,Yes,Yes,Poor
996,D30996,23,3.0,1.10,1,10.7,7.5,31.0,1,34.0,...,Student,United States,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Fair
997,D30997,15,28.0,4.38,1,30.6,9.2,20.0,0,100.0,...,Employed Full-time,United States,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Good
998,D30998,22,23.0,1.84,0,27.9,6.9,41.0,2,45.0,...,Student,India,Tablet,Watching Videos,No,Yes,Yes,Yes,No,Fair
999,D30999,23,35.0,1.66,2,16.2,7.5,27.0,2,63.0,...,Employed Full-time,India,Tablet,Scrolling Social Media,No,Yes,Yes,No,Yes,Fair


In [ ]:
!git clone https://github.com/vasist05/eda-colab-lab.git



fatal: destination path 'eda-colab-lab' already exists and is not an empty directory.
fatal: not a git repository (or any of the parent directories): .git


In [ ]:
%cd eda-colab-lab
!git status

/content/eda-colab-lab
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


#Week-6: (18/8/26, Tue) : Sorting, Ranking



1)Create a pandas.Series of student grades: ['A', 'B', 'C', 'A', 'D', 'B', 'C', 'F'].
 Map letter grades to numeric values using a dictionary:
 {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}.
  Display the numeric grades.


In [8]:
import pandas as pd
s=pd.Series(['A', 'B', 'C', 'A', 'D', 'B', 'C', 'F'])
print(s)
#mapping
m=s.map( {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0})
print(m)

0    A
1    B
2    C
3    A
4    D
5    B
6    C
7    F
dtype: object
0    4
1    3
2    2
3    4
4    1
5    3
6    2
7    0
dtype: int64


3)Create a DataFrame with columns:
  Name = ['Alice', 'Bob', 'Charlie', 'David', 'Eva']  Marks = [87, 45, 67, 92, 78]
<br> Sort the DataFrame:
<br>  By Marks in ascending order.
<br> By Marks in descending order.
<br> By Name alphabetically.


In [21]:
df1=pd.DataFrame({"Name":['Alice', 'Bob', 'Charlie', 'David', 'Eva'],"Marks":[87, 45, 67, 92, 78]})
# sorting by marks in ascde
df2=df1.sort_values("Marks")
print(df2,"\n")
# sorting by marks in descending
df3=df1.sort_values("Marks",ascending=False)
print(df3)
print()
df4=df1.sort_values("Name")
print(df4)


      Name  Marks
1      Bob     45
2  Charlie     67
4      Eva     78
0    Alice     87
3    David     92 

      Name  Marks
3    David     92
0    Alice     87
4      Eva     78
2  Charlie     67
1      Bob     45

      Name  Marks
0    Alice     87
1      Bob     45
2  Charlie     67
3    David     92
4      Eva     78


Create a DataFrame of products with columns: ['Product', 'Price', 'Rating'].
<br>Sort first by Price (ascending), then by Rating (descending).


In [29]:
df5=pd.DataFrame({"product":["oreo","vim","benz","calc"],"price":[104,51,500000,2000],"rating":[3,4,5,2]})
print(df5,"\n")
df6=df5.sort_values("price")
print(df6,"\n")
df7=df5.sort_values("rating",ascending=False)
print(df7)


  product   price  rating
0    oreo     104       3
1     vim      51       4
2    benz  500000       5
3    calc    2000       2 

  product   price  rating
1     vim      51       4
0    oreo     104       3
3    calc    2000       2
2    benz  500000       5 

  product   price  rating
2    benz  500000       5
1     vim      51       4
0    oreo     104       3
3    calc    2000       2


###Ranking Data
a) Create a Series of student scores [87, 92, 45, 76, 92, 60].
<br>   Use rank() to assign ranks (average ranking method).
<br>   Use rank(method='first') and compare.




In [33]:

s = pd.Series([87, 92, 45, 76, 92, 60])
print(s)
print()
print(s.rank())
print()
print(s.rank(method='first'))

0    87
1    92
2    45
3    76
4    92
5    60
dtype: int64

0    4.0
1    5.5
2    1.0
3    3.0
4    5.5
5    2.0
dtype: float64

0    4.0
1    5.0
2    1.0
3    3.0
4    6.0
5    2.0
dtype: float64
